### ISSUE TITLE
not clear why one would set the pusher / gcm 

### ISSUE THREAD

**Issue by vesper8** [cretueusebiu/laravel-web-push-demo#14]
Could anyone explain in which scenario would it be necessary / useful to set the GCM / PUSHER keys since they are optional?

**Comment by cretueusebiu** [comment]
The GCM keys can be used for compatibility  with older versions of the package. If you never used GCM then you don't have to use them.

The Pusher keys are just for demo purposes, the get the web notifications in real time.
