### ISSUE TITLE
Endpoint truncated 

### ISSUE THREAD

**Issue by kombany** [cretueusebiu/laravel-web-push-demo#15]
I got this error 
![screenshot 1](https://user-images.githubusercontent.com/30722877/36591213-86c259c4-1891-11e8-9795-6768430d68e6.png)
(url)

**Comment by cretueusebiu** [comment]
You have to look at the server response in the Network tab.

**Comment by kombany** [comment]
![screenshot 2](https://user-images.githubusercontent.com/30722877/36591738-38b06b70-1893-11e8-9c28-ae44242d9d88.png)

**Comment by cretueusebiu** [comment]
You have to click on the response tab.

**Comment by kombany** [comment]
![screenshot 3](https://user-images.githubusercontent.com/30722877/36592009-447545f6-1894-11e8-944e-8acd802714be.png)

**Comment by cretueusebiu** [comment]
Edit [this migration](https://github.com/cretueusebiu/laravel-web-push-demo/blob/master/database/migrations/2016_08_11_191827_create_push_subscriptions_table.php) and change 

```php
$table->string('endpoint')->unique();
```
to
```php
$table->text('endpoint')->unique();
```

You'll have to migrate everything all over again.

**Comment by kombany** [comment]
![screenshot 4](https://user-images.githubusercontent.com/30722877/36592820-93c4633c-1897-11e8-91b7-612b1c4d386e.png)

**Comment by kombany** [comment]
now the header is notification sent .... but have to refresh to whole page to see the notification

**Comment by kombany** [comment]
in firefox and chrome too

**Comment by cretueusebiu** [comment]
You have to enable Pusher.

**Comment by kombany** [comment]
where or how ?

**Comment by cretueusebiu** [comment]
https://github.com/cretueusebiu/laravel-web-push-demo#installation

 Set `PUSHER_APP_ID`, `PUSHER_APP_KEY`, `PUSHER_APP_SECRET` from pusher.com

**Comment by kombany** [comment]
actually you wrote that's optional however still a same story I have to refresh the page

**Comment by kombany** [comment]
![screenshot 5](https://user-images.githubusercontent.com/30722877/36594189-7561a426-189d-11e8-8702-a3e11a08e02d.png)

**Comment by kombany** [comment]
if I refresha page I always get a notification where is a time is 2 days ago

**Comment by kombany** [comment]
![screenshot 6](https://user-images.githubusercontent.com/30722877/36594383-3768d576-189e-11e8-85db-c5392ce0b63c.png)

**Comment by cretueusebiu** [comment]
Might be something wrong with the timezone on your server. Make sure to use UTC.

**Comment by kombany** [comment]
ow it's send twice every message

**Comment by kombany** [comment]
forget it

**Comment by kombany** [comment]
too many problems with your mvc reusable code :)

**Comment by cretueusebiu** [comment]
Try just using the package behind this demo https://github.com/laravel-notification-channels/webpush 

Not sure why you're having so many problems...

**Comment by kombany** [comment]
please note that to installation : migration won't work if you clone this repo ... however migration will run but you give an error message, and please note the server requirements .. cuz somebody will try this code in apache and linux ... so the requirements it's so  ipmprotant and you and so on ...
