### ISSUE TITLE
app.js:33556 WebSocket connection to 'ws://ws.pusherapp.com/app/67006e7ceebb6ff4d753' failed: Invalid frame header

### ISSUE THREAD

**Issue by qodeanil** [cretueusebiu/laravel-web-push-demo#16]
I have installed your Laravel package for pusher in my application. however, i am getting the issue as  

_app.js:33556 WebSocket connection to 'ws://ws.pusherapp.com/app/67006e7ceebb6ff4d753?protocol=7&client=js&version=4.2.2&flash=false' failed: Invalid frame header  WebSocket connection to 'ws://ws.pusherapp.com/app/67006e7ceebb6ff4d753?protocol=7&client=js&version=4.2.2&flash=false' failed:_  

**WebSocket is closed before the connection is established.**  

**Whereas "Enable Push Notification" Button is always disabled.** Please let me know how I can solve this issue.

![screen shot 2018-03-15 at 8 10 24 pm](https://user-images.githubusercontent.com/16719253/37471295-87400f44-2891-11e8-9b15-8d2825e721d7.png)
![screen shot 2018-03-15 at 8 10 09 pm](https://user-images.githubusercontent.com/16719253/37471296-877c120a-2891-11e8-8cb0-36edd08b3f9b.png)

**Comment by cretueusebiu** [comment]
Do you have SSL ?

**Comment by qodeanil** [comment]
no i dont have SSL.

**Comment by cretueusebiu** [comment]
SSL is required for web push api.

**Comment by qodeanil** [comment]
ok let me have ssl in my domain and find if this works. thanks for your suggestion
