### ISSUE TITLE
app.js:897 POST http://localhost:8000/chat/sendChat 500 (Internal Server Error)

### ISSUE THREAD

**Issue by kfiroj** [cretueusebiu/laravel-web-push-demo#17]
this error was showing in console when I tried to send a message to another person it give me this error and message is not delivered to him but when I refresh the page all work correctly message is also delivered to another person why this is happen.

this is all showing in console
POST http://localhost:8000/chat/sendChat 500 (Internal Server Error)
dispatchXhrRequest @ app.js:897
xhrAdapter @ app.js:731
dispatchRequest @ app.js:29721
Promise.then (async)
request @ app.js:29177
Axios.(anonymous function) @ app.js:29197
wrap @ app.js:520
sendChat @ app.js:46495
keyup @ app.js:46534
invoker @ app.js:36935
fn._withTask.fn._withTask @ app.js:36734
app.js:922 Uncaught (in promise) Error: Request failed with status code 500
    at createError (app.js:922)
    at settle (app.js:29249)
    at XMLHttpRequest.handleLoad (app.js:796)
createError @ app.js:922
settle @ app.js:29249
handleLoad @ app.js:796
Promise.then (async)
sendChat @ app.js:46495
keyup @ app.js:46534
invoker @ app.js:36935
fn._withTask.fn._withTask @ app.js:36734

**Comment by cretueusebiu** [comment]
You'll have to be more specific. Inspect the server response, check the logs.

**Comment by kfiroj** [comment]
@cretueusebiu  ya I checked but it showing same error I think the event is not working because it save the message in database but doesn't reflect to chat window , when I refresh the page it get chats from database and then it show.

**Comment by cretueusebiu** [comment]
I think you're confusing the scripts, this is not related to chat.

**Comment by kfiroj** [comment]
![c](https://user-images.githubusercontent.com/36274874/38795708-ba6effe4-4176-11e8-8684-78f8067b1338.png)

**Comment by kfiroj** [comment]
![d](https://user-images.githubusercontent.com/36274874/38795767-e475dfba-4176-11e8-9c38-856a383dadda.png)

**Comment by kfiroj** [comment]
this error I am getting

**Comment by cretueusebiu** [comment]
Sorry, can't help with custom apps.

**Comment by kfiroj** [comment]
@cretueusebiu thats ok
