### ISSUE TITLE
How do you broadcast notification to all users?

### ISSUE THREAD

**Issue by milanchheda** [cretueusebiu/laravel-web-push-demo#22]
So I've installed the package and was able to send / receive notifications in desktop as well as mobile. But, it only works when logged in person has enabled notifications and the same logged in person is sending the notification. 

I want admin to send notifications to all users. What changes do I need to make in this case?

**Comment by cretueusebiu** [comment]
Instead of `$request->user()->notify(new HelloNotification);` you'd have `Notification::send($users, new HelloNotification);`.

See https://laravel.com/docs/5.6/notifications#sending-notifications

**Comment by milanchheda** [comment]
Thanks @cretueusebiu .. That was quick! :+1:
