### ISSUE TITLE
[Feature Request] Upgrade to Laravel 5.6

### ISSUE THREAD

**Issue by sotisoti** [cretueusebiu/laravel-web-push-demo#23]
Is it possible to upgrade the project to Laravel 5.6?  I try npm run dev/production but the generated app.js doesn't work and as a workaround, I have to copy the /public/app.js in the current repo (5.5) to my project (5.6)

**Comment by cretueusebiu** [comment]
This is just a demo, but the webpush library works with the latest version of Laravel. 

So if you want to upgrade this demo just follow the Laravel upgrade guide.

A will upgrade it at some point, but for now for a demo should work just fine.

**Comment by Braunson** [comment]
@cretueusebiu Tab this as #hacktoberfest .. https://hacktoberfest.digitalocean.com/ ;-)
