### ISSUE TITLE
Illegal Instruction: 4

### ISSUE THREAD

**Issue by junedc** [cretueusebiu/laravel-web-push-demo#24]
I have cloned and followed the steps except adding pusher and gcm keys 
since it said optional.

set my database to sqlite

when I run php artisan webpush:vapid

It gives me Illegal instruction: 4

This is my php-v results
PHP 7.1.10 (cli) (built: Oct  2 2017 08:58:21) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.10, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.3, Copyright (c) 2002-2017, by Derick Rethans

**Comment by cretueusebiu** [comment]
Please post the full exception.
