### ISSUE TITLE
Service workers aren't supported in this browser.

### ISSUE THREAD

**Issue by Braunson** [cretueusebiu/laravel-web-push-demo#25]
Receiving `Service workers aren't supported in this browser.` in console, running Chrome Version 69.0.3497.100 (Official Build) (64-bit) on Windows.

Even when in console running `'serviceWorker' in navigator` returns false. Any idea why?

**Comment by cretueusebiu** [comment]
https://groups.google.com/a/chromium.org/forum/m/#!topic/service-worker-discuss/Cohd-TKG8so

**Comment by Braunson** [comment]
@cretueusebiu I can confirm I'm not blocking cookies. I've even tried clearing cookies without resolve.

**Comment by cretueusebiu** [comment]
https://stackoverflow.com/questions/52299246/cant-find-serviceworker-in-navigator-anymore
