### ISSUE TITLE
Hi, composer require laravel-notification-channels/webpush doesn`t work

### ISSUE THREAD

**Issue by vitaliy-svyrydov** [cretueusebiu/laravel-web-push-demo#27]
Problem 1 - laravel-notification-channels/web push 3.0.0 requires minish link/web-push ^2.0 -> satisfiable by minishlink/web-push[v2.0.0, v2.0.1]. - laravel-notification-channels/webpush 3.0.1 requires minishlink/web-push ^2.0 -> satisfiable by minishlink/web-push[v2.0.0, v2.0.1]. - minishlink/web-push v2.0.0 requires mdanter/ecc ^0.5.0 -> satisfiable by mdanter/ecc[v0.5.0]. - minishlink/web-push v2.0.1 requires mdanter/ecc ^0.5.0 -> satisfiable by mdanter/ecc[v0.5.0]. - mdanter/ecc v0.5.0 requires ext-gmp * -> the requested PHP extension gmp is missing from your system. - Installation request for laravel-notification-channels/webpush ^3.0 -> satisfiable by laravel-notification-channels/webpush[3.0.0, 3.0.1].

After receiving this error, I try to install everything I need for the package.But after trying to install I get errors

**Comment by cretueusebiu** [comment]
> the requested PHP extension gmp is missing from your system.

You need to install the `gmp` PHP extension.
