### ISSUE TITLE
Not working in realtime

### ISSUE THREAD

**Issue by arbnorsalihu** [cretueusebiu/laravel-web-push-demo#45]
Hello, 
Thank you for your project. It is working good but I have a problem for working in realtime. It is not working in realtime. I have to refresh the page to get the notifications.
I have made the configuration for .env file and all other configuration files based on your description but it doesn't work.
I'm using Laravel 5.7

Thank you in advance

**Comment by arbnorsalihu** [comment]
Solved! I had to edit broadcating.php to this:
'options' => [
              'cluster' => 'eu',
              'encrypted' => false
            ],

**Comment by connecteev** [comment]
@arbnorsalihu I'm seeing the same problem. The Chrome push notifications come in when I press "Send Notification", but the number on the 'bell' icon doesnt update unless I refresh the page.

I changed my broadcasting.php file but that didnt help:
```

    'connections' => [

        'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_CLUSTER', 'us'),
                'encrypted' => false
            ],
        ],

```
What else did you change?

**Comment by cretueusebiu** [comment]
Make sure to set the Pusher keys and `BROADCAST_DRIVER=pusher`

**Comment by connecteev** [comment]
@cretueusebiu oops! thank you, I was missing BROADCAST_DRIVER=pusher. That fixed it.

**Comment by amirreza1751** [comment]
Does laravel-web-push use pusher server?
