### ISSUE TITLE
Not Receiving Notifications

### ISSUE THREAD

**Issue by Neve12ende12** [cretueusebiu/laravel-web-push-demo#48]
Is there anything I need to setup with any external services? Does this not work on localhost? Am I required to use pusher? Everything seems to be working. I am able to save and delete my endpoints from the database. I even get the 201 when sending the notification; however, I never receive the notification.

**Comment by Neve12ende12** [comment]
It does not work on localhost.

**Comment by mwhitney9** [comment]
I am also having trouble with this - I think when running php artisan migrate I get 

"  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too l
  ong; max key length is 767 bytes (SQL: alter table `subscriptions` add unique `
  subscriptions_endpoint_unique`(`endpoint`))
"

Then when running it again, I get 

" SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'subscriptions'
  already exists (SQL: create table `subscriptions` (`id` int unsigned not null a
  uto_increment primary key, `subscribable_type` varchar(191) not null, `subscrib
  able_id` bigint unsigned not null, `endpoint` varchar(500) not null, `public_ke
  y` varchar(191) null, `auth_token` varchar(191) null, `content_encoding` varcha
  r(191) null, `created_at` timestamp null, `updated_at` timestamp null) default
  character set utf8mb4 collate 'utf8mb4_unicode_ci')
"

The table is created, then it will not work past this point. The notifications work, but only on reload and no subscription comes in
