### ISSUE TITLE
No browser notifications

### ISSUE THREAD

**Issue by mwhitney9** [cretueusebiu/laravel-web-push-demo#49]
Hello,

Hoping to find a solution to my problem. Please see below - the browser notifications do not appear, and the application only shows notifications on reload.

I am also having trouble with this - I think when running php artisan migrate I get

" SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too l
ong; max key length is 767 bytes (SQL: alter table subscriptions add unique subscriptions_endpoint_unique(endpoint))
"

Then when running it again, I get

" SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'subscriptions'
already exists (SQL: create table subscriptions (id int unsigned not null a
uto_increment primary key, subscribable_type varchar(191) not null, subscrib able_id bigint unsigned not null, endpoint varchar(500) not null, public_ke y varchar(191) null, auth_token varchar(191) null, content_encoding varcha
r(191) null, created_at timestamp null, updated_at timestamp null) default
character set utf8mb4 collate 'utf8mb4_unicode_ci')
"

The table is created, then it will not work past this point.

Thank you!

**Comment by JoeMito** [comment]
I got real time notification when using with Pusher API, but only user itself. the other user currently login in would not

> Hello,
> 
> Hoping to find a solution to my problem. Please see below - the browser notifications do not appear, and the application only shows notifications on reload.
> 
> I am also having trouble with this - I think when running php artisan migrate I get
> 
> " SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too l
> ong; max key length is 767 bytes (SQL: alter table subscriptions add unique subscriptions_endpoint_unique(endpoint))
> "
> 
> Then when running it again, I get
> 
> " SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'subscriptions'
> already exists (SQL: create table subscriptions (id int unsigned not null a
> uto_increment primary key, subscribable_type varchar(191) not null, subscrib able_id bigint unsigned not null, endpoint varchar(500) not null, public_ke y varchar(191) null, auth_token varchar(191) null, content_encoding varcha
> r(191) null, created_at timestamp null, updated_at timestamp null) default
> character set utf8mb4 collate 'utf8mb4_unicode_ci')
> "
> 
> The table is created, then it will not work past this point.
>
> Thank you!

Hai,

I got real time notification when using Pusher API, but only work current user. The user in other browser need to reload page. Maybe need to tweak some coding in js component. Will update soon...

SQLSTATE[42000]: Syntax error or access violation: 1071.......
This happen when you put too much data in toWebPush function in body at HelloNotifcation for example, you put image in body. Put small byte data only. In toArray function, you allowed to put large data in the body.

You don't need to re-migrate migrated table. if you want too, you can do php artisan refresh, to delete current table, the migrate new or delete table in database, then migrate.
