### ISSUE TITLE
app.js:33 Uncaught (in promise) TypeError

### ISSUE THREAD

**Issue by Jagdish2** [cretueusebiu/laravel-web-push-demo#5]
I just download the demo project ad done as it's step but it give error.
Help me asap.
**Thax**

> 

app.js:33 Uncaught (in promise) TypeError: Cannot read property 'socketId' of undefined
 at app.js:33
(anonymous) @ app.js:33

/sw.js:1 A bad HTTP response code (404) was received when fetching the script.
http://localhost/sw.js Failed to load resource: net::ERR_INVALID_RESPONSE

home:1 Uncaught (in promise) TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.
![image](https://cloud.githubusercontent.com/assets/23050806/22418718/347e9222-e700-11e6-83a4-18edebeb3065.png)

**Comment by cretueusebiu** [comment]
You need to configure a domain because right now you access it via a folder and that breaks the Laravel router. Also make sure you have SSL on your domain otherwise the Push Api won't work.
