### ISSUE TITLE
In ECKey.php line 148:   Unable to create the key  

### ISSUE THREAD

**Issue by metalsadman** [cretueusebiu/laravel-web-push-demo#63]
getting error: 

In ECKey.php line 148:  
Unable to create the key  

when running php artisan webpush:vapid.

**Comment by vtscarlos** [comment]
Same error

**Comment by cretueusebiu** [comment]
The error originates from here:
https://github.com/web-push-libs/web-push-php/blob/8911bad58026db19ab5e39d19341ea9925cb1edb/src/Encryption.php#L312

Basically your installation of PHP + OpenSSL is  misconfigured and [openssl_pkey_new](https://www.php.net/manual/en/function.openssl-pkey-new.php) returns false.
