### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'socketId' of undefined

### ISSUE THREAD

**Issue by davidnash** [cretueusebiu/laravel-web-push-demo#7]
I've followed the instructions and everything went well.

However when I load the page I get this JS error:

`Uncaught (in promise) TypeError: Cannot read property 'socketId' of undefined at app.js:formatted:17480
`

and both buttons are disabled.

The pretty-printed line where the error occurs is:

`config.headers['X-Socket-ID'] = window.Echo.socketId();`

Server is running on localhost, I see the error at http://localhost/home.

Thanks for your help!

**Comment by cretueusebiu** [comment]
Can you show the lines above/bellow that line to see exactly where it happens ?

**Comment by davidnash** [comment]
Thanks for looking into it.

Here's the code block it's in:

```
__WEBPACK_IMPORTED_MODULE_2_axios___default.a.interceptors.request.use(function (config) {
  config.headers['X-Socket-ID'] = window.Echo.socketId();
  return config;
}, function (error) {
  return Promise.reject(error);
});
/* WEBPACK VAR INJECTION */}.call(__webpack_exports__, __webpack_require__(1)))
```

Which I assume is coming from the code in resources/assets/js/bootstrap.js.

**Comment by cretueusebiu** [comment]
That happens when you don't configure Pusher (even though it's optional). Do a `git pull` and try again.

**Comment by davidnash** [comment]
No worries, it's working now, thanks! 

To get it working I have to comment out `Options -Multiviews` in public/.htaccess because I get Error 500 "Options not allowed here" in Apache 2.4.18

But I can live with that!
