### ISSUE TITLE
how to put working the notification like image on browser

### ISSUE THREAD

**Issue by drolean** [cretueusebiu/laravel-web-push-demo#8]
Hi...
Nice work for this demo code and package, i'm trying to get working this.
but i need only icon notification without reload like image demo on chrome...

how to this???

https://my.mixtape.moe/hlypcc.gif

apologies my english ^^

**Comment by cretueusebiu** [comment]
Have you configured Pusher ?

**Comment by drolean** [comment]
yeah configured, i see on pusher debug console my connection.

**Comment by cretueusebiu** [comment]
Have you checked the network tab? Do you get any errors ? Make sure you've set the Pusher region too.

**Comment by thaibeouu** [comment]
@cretueusebiu I'm having the same problem, `pusher` is properly configured I guess

**Comment by cretueusebiu** [comment]
Make sure it's configured according to the docs https://laravel.com/docs/5.4/broadcasting
