### ISSUE TITLE
Installing demo inside a sub directory breaks app.js

### ISSUE THREAD

**Issue by jitheshkt** [cretueusebiu/laravel-web-push-demo#9]
Installing demo in to a sub directory of root domain breaks app.js (some where around it calls for <rootdomain>notifications and gets 404 as the project is inside a sub directory) Could you please add non-minified version of app.js ?

**Comment by cretueusebiu** [comment]
The source can be found [here](https://github.com/cretueusebiu/laravel-web-push-demo/tree/master/resources/assets/js). 

You should use the `asset` function in [app.blade.php](https://github.com/cretueusebiu/laravel-web-push-demo/blob/master/resources/views/layouts/app.blade.php) so it uses the full url.
